### ISSUE TITLE
提示“获取失败”

### ISSUE THREAD

**Issue by pdnfm** [pwp-app/steam-emoji-extractor#1]
![微信图片_20220616014047](https://user-images.githubusercontent.com/37098401/173891167-858ea72c-0a3b-477b-a568-60add24384ae.png)

**Comment by backrunner** [comment]
相关的worker有ssl相关的问题，正在联系Cloudflare寻求支持。
如果问题没解决晚上我再临时处理一下。

**Comment by backrunner** [comment]
计划顺手切一个域名，后续发布新版本了再close

**Comment by backrunner** [comment]
新版本已上线
